import fs from "node:fs";
import path from "node:path";
import type {
  Bracket,
  Groups,
  Meta,
  MontecastData,
  Simulation,
  TeamInfo,
} from "./types";

const DATA_DIR = path.join(process.cwd(), "public", "data");

function read<T>(file: string): T {
  return JSON.parse(fs.readFileSync(path.join(DATA_DIR, file), "utf-8")) as T;
}

/** Load all forecast artifacts at build time (regenerated by the Python engine). */
export function loadData(): MontecastData {
  return {
    meta: read<Meta>("meta.json"),
    teams: read<TeamInfo[]>("teams.json"),
    simulation: read<Simulation>("simulation.json"),
    groups: read<Groups>("groups.json"),
    bracket: read<Bracket>("bracket.json"),
  };
}
